export const actions = {
  LLENAR_MENTORIA: "LLENAR_MENTORIA",
  LLENAR_SESION: "LLENAR_SESION",
  LLENAR_REVISION: "LLENAR_REVISION",
  POST_MENTORIA: "POST_MENTORIA",
  POST_MENTORIA_SUCCESS: "POST_MENTORIA_SUCCESS",
  POST_MENTORIA_ERROR: "POST_MENTORIA_ERROR",
  POST_SESION: "POST_SESION",
  POST_SESION_SUCCESS: "POST_SESION_SUCCESS",
  POST_SESION_ERROR: "POST_SESION_ERROR",
  POST_REVISION: "POST_REVISION",
  POST_REVISION_SUCCESS: "POST_REVISION_SUCCESS",
  POST_REVISION_ERROR: "POST_REVISION_ERROR",
};
